#ifndef FLAPPY_ASSETS_H
#define FLAPPY_ASSETS_H

static const char *const bird_climb_hard_xpm[] = {
    "16 12 5 1",
    ". c None",
    "Y c #F2C94C",
    "O c #F2994A",
    "W c #FFFFFF",
    "K c #1F2933",
    "................",
    ".........YYYOO..",
    ".......YYYYYYO..",
    ".....YYYYYWKYY..",
    "...YYYYYYKKYYY..",
    "..YYYYYYYYYYYY..",
    ".YYYYYYYYYYY....",
    "YYYYYYYYY.......",
    ".YYYYYY.........",
    "..YYY...........",
    "................",
    "................",
};

static const char *const bird_climb_xpm[] = {
    "16 12 5 1",
    ". c None",
    "Y c #F2C94C",
    "O c #F2994A",
    "W c #FFFFFF",
    "K c #1F2933",
    "................",
    ".......YYYYOO...",
    ".....YYYYYYYO...",
    "...YYYYYYWKYY...",
    "..YYYYYYYKKYYY..",
    ".YYYYYYYYYYYYY..",
    ".YYYYYYYYYYYY...",
    "..YYYYYYYYY.....",
    "....YYYYYY......",
    ".....YYY........",
    "................",
    "................",
};

static const char *const bird_flat_xpm[] = {
    "16 12 5 1",
    ". c None",
    "Y c #F2C94C",
    "O c #F2994A",
    "W c #FFFFFF",
    "K c #1F2933",
    "................",
    ".....YYYYYY.....",
    "...YYYYYYYYYY...",
    "..YYYYYYYYYYYY..",
    ".YYYYYYYYYWKYYO.",
    "YYYYYYYYYYYKKYOO",
    ".YYYYYYYYYYYYYO.",
    "..YYYYYYYYYYYY..",
    "...YYYYYYYYYY...",
    ".....YYYYYY.....",
    "................",
    "................",
};

static const char *const bird_dive_xpm[] = {
    "16 12 5 1",
    ". c None",
    "Y c #F2C94C",
    "O c #F2994A",
    "W c #FFFFFF",
    "K c #1F2933",
    "................",
    "................",
    ".....YYY........",
    "....YYYYYY......",
    "..YYYYYYYYY.....",
    ".YYYYYYYYYYYY...",
    ".YYYYYYYYYYYYY..",
    "..YYYYYYYKKYYY..",
    "...YYYYYYWKYYO..",
    ".....YYYYYYYO...",
    ".......YYYYOO...",
    "................",
};

static const char *const bird_dive_hard_xpm[] = {
    "16 12 5 1",
    ". c None",
    "Y c #F2C94C",
    "O c #F2994A",
    "W c #FFFFFF",
    "K c #1F2933",
    "................",
    "................",
    "................",
    "..YYY...........",
    ".YYYYYY.........",
    "YYYYYYYYY.......",
    ".YYYYYYYYYYY....",
    "..YYYYYYYYYYYY..",
    "...YYYYYYKKYYY..",
    ".....YYYYYWKYYO.",
    ".......YYYYYYO..",
    ".........YYYOO..",
};

static const char *const pipe_xpm[] = {
    "24 64 4 1",
    ". c None",
    "G c #49A35B",
    "D c #2E7D3F",
    "L c #7BD889",
    "DDDDDDDDDDDDDDDDDDDDDDDD",
    "DLLLLLLLLLLLLLLLLLLLLLLD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DGGGGGGGGGGGGGGGGGGGGGGD",
    "DLLLLLLLLLLLLLLLLLLLLLLD",
    "DDDDDDDDDDDDDDDDDDDDDDDD",
};

#endif
